### PR TITLE
Added root support to HepMC3

### PR DESCRIPTION
**Pull request by andriish**
Hi Delphes team,

I've just noticed you have added HepMC3 to the source tree and decided to create this pull request for your consideration.

Briefly, this PR adds support of root I/O via HepMC3. This is a much more efficient way to read and write the generated MC samples than just a plain ASCII, i.e. Ascii and  AsciiHepMC2.

Hopefully, this will be beneficial for Delphes.

Best regards,

Andrii

### CODE REVIEW

**Comment by pavel-demin** [comment]
Thank you for your effort but I don't see how it can be beneficial.

I'd prefer to keep the directory structure in external/HepMC3 as I created it. The current version of this pull request moves and renames many files.

Moreover, I am considering including the HepMC3 library as a temporary fix to urgently include HepMC3 support. Hopefully the dependency on the HepMC3 library will be removed once I find out how to handle HepMC3 more efficiently.

**Comment by andriish** [comment]
Hi @pavel-demin ,

> moves and renames many files 

It is closer to the HepMC3 source tree structure -- easier to sync with the upstream. 

> how to handle HepMC3 more efficiently 

do you mean having it as an external dependency? That would be, indeed, a much cleaner approach.


Best regards,

Andrii

**Comment by pavel-demin** [comment]
> easier to sync with the upstream

It's not a requirement.

> do you mean having it as an external dependency?

No. The idea is not to depend on the HepMC3 library at all. 

HepMC3 is slow. I have a reader ([DelphesHepMC3Reader.cc](https://github.com/delphes/delphes/blob/master/classes/DelphesHepMC3Reader.cc)) of the HepMC3 format that is significantly faster. The problem is that HepMC3 is more broken than HepMC2 and the products of the decays in HepMC3 are sometimes ordered and sometimes not. Once I find out how to do the reordering in an efficient way of the products of the decays, I'll add it to [DelphesHepMC3Reader.cc](https://github.com/delphes/delphes/blob/master/classes/DelphesHepMC3Reader.cc) and remove the HepMC3 library.

**Comment by andriish** [comment]
> HepMC3 is slow. 

Do you mean reading? Well, the Ascii readers are not slower than in HepMC2 and the  ROOT readers are much faster.
That was tested on multiple samples,see https://arxiv.org/pdf/1912.08005.pdf  Figures 2 and 3.

> DelphesHepMC3Reader.cc

 But that implements just a subset of HepMC3. And actually would read only a subset of HepMC2 *information*, e.g. weight names are missing, vector of random number seeds is missing, no polarization, colour flows.
While colour flows are not relevant, the names of weights are.

> the products of the decays in HepMC3 are sometimes ordered and sometimes not. 

What do you mean? The particles are always ordered in topological order in HepMC3 (if the event is correctly written). In HepMC2 these are not ordered at all.


Best regards,

Andrii

**Comment by pavel-demin** [comment]
> Do you mean reading?

Yes, I think only reading is relevant for Delphes.

> Well, the Ascii readers are not slower than in HepMC2 and the ROOT readers are much faster.

HepMC2 was also slow. I even created a bug report (http://savannah.cern.ch/bugs/?98781, http://savannah.cern.ch/task/?40898) in 2012 showing that it was possible to read the HepMC2 files 3 times faster. Unfortunately, the HepMC2 developers lost interest in the development of the HepMC2 library and never implemented the faster readout.

The idea was to implement an equivalent of istringstream using the strtod/strtol functions and
then replace istringstream with this new stream class. Unfortunately, the HepMC3 library doesn't use istringstream anymore. So, fixing its performance would be less trivial than it was in the HepMC2 library.

BTW. For me, the main advantage of the HepMC format is that it is human readable and does not require ROOT or other non-standard libraries to read files. Using ROOT to read and write HepMC files doesn't make much sense to me. It adds a very heavy dependency to all MC generators that use HepMC. If a binary format is required, then there are already STDHEP, ProMC, ProIO.

> While colour flows are not relevant, the names of weights are.

Delphes doesn't use the weights names at the moment.

The point is that the HepMC libraries use slow methods to read and parse the files and the developers weren't interested to implement faster methods.

> What do you mean? The particles are always ordered in topological order in HepMC3 (if the event is correctly written). In HepMC2 these are not ordered at all.

I'd say I have quite an opposite experience. Maybe our definitions of "ordered" differ. I'll try to illustrate the problem with a few lines of the same event in HepMC2 and HepMC3 format. Both examples were created with HepMC 3.2.3. Here is a [link](http://cp3.irmp.ucl.ac.be/~demin/test.hepmc.gz) to the full file that I used to create the files for this test.

HepMC2 decay with ordered (in my understanding) decay products:
```
P 10014 21 3.0475622025960547e-14 -1.4960255256823984e-14 -5.4950461969738093e+01 5.4950461969738086e+01 0.0000000000000000e+00 41 0 0 -11 2 1 103 2 108
...
V -11 0 0 0 0 0 0 2 0
P 10018 21 2.1660451210436804e-13 -9.4146912488213275e-14 -4.9784554224732538e+01 4.9784554224732517e+01 0.0000000000000000e+00 42 0 0 -12 2 1 103 2 102
P 10019 21 8.7047004749495216e-01 -4.2676088055794892e-01 -5.0974673471196814e+00 5.1888357372065474e+00 0.0000000000000000e+00 43 0 0 -64 2 1 102 2 108
```

In the HepMC2 format, the decay products have decay products have consecutive numbers and follow each other.

HepMC3 decay:
```
P 14 7 21 3.0475622025960547e-14 -1.4960255256823984e-14 -5.4950461969738093e+01 5.4950461969738086e+01 0.0000000000000000e+00 41
...
P 18 14 21 2.1660451210436804e-13 -9.4146912488213275e-14 -4.9784554224732538e+01 4.9784554224732517e+01 0.0000000000000000e+00 42
...
P 84 14 21 8.7047004749495216e-01 -4.2676088055794892e-01 -5.0974673471196814e+00 5.1888357372065474e+00 0.0000000000000000e+00 43
```

In the HepMC3 format, the decay products can be anywhere in the event.

**Comment by pavel-demin** [comment]
> If actually there is a case when the particles are ordered in a wrong way, that makes sense to submit a bugreport

I don't know if it's a bug. Unlike HepMC2, the HepMC3 document does not specify how decay products are to be ordered. So to me that looks like a feature that unfortunately makes the HepMC3 format less readable by both human and machine.

Personally, I would be happy to see a new version (HepMC4) of the format that combines the good parts of HepMC2 (vertices and particles) and HepMC3 (attributes and weights).

**Comment by andriish** [comment]
> I even created a bug report (
> http://savannah.cern.ch/bugs/?98781, 
> http://savannah.cern.ch/task/?40898) in 

Ok, even I was unaware of that page and all these tickets.
As far as I understand, the 2.07.xx had some of these features implemented, but then, at some point, there was no reason to make 2.07.00 release, as it would not be compatible with 2.06.xx and 3.xx.

>the main advantage of the HepMC format is that it is
> human readable and does not require ROOT or other non-standard
> libraries to read files. Using ROOT to read and write HepMC files
> doesn't make much sense to me. It adds a very heavy dependency to all
> MC generators that use HepMC. If a binary format is required, then
> there are already STDHEP, ProMC, ProIO.

How good or bad the data is compressed and even how fast can be red has little relevance for the adoption of *any* library by MC generators. The most important part is the ability to store the information in a reliable, compatible way and the availability of actual interfaces. For most modern MCEGs the I/O of an event is just a tiny fraction of CPU time used for event generation. That is the case for many MC-related tools. I'm quite surprised that is not the case for Delphes. Or is it?
If it actually is, then one can try to speedup the reaing.

But, probably the fasters way to read the events inside Delphes still would be to read HepMC3 ROOT trees directly with ROOT, without HepMC3. This is *really* fast, as not reconstruction of event structure is needed. See

In the HepMC2 example the 10019 and 10018 are not even  "id"s, but just arbitrary "barcodes" of particles and they are not necessarily consequent in the decays. One cannot rely on that.

In HepMC3 the ordering is that parents have smaller "id" than children. But the "id" itself is not important. It is not even a part of the particle information.

> Unlike HepMC2, the HepMC3 document does not specify how decay products are to be ordered.

Because the event structure is a graph and is decoupled from the  I/O.  The set of statements 
```
Particle A was produced in vertex V
Particle B was produced in vertex V
 ```
is equivalent to 
```
Particle B was produced in vertex V
Particle A was produced in vertex V
 ```
The way how the event structure is serialized to disk is defined in the corresponding  `Writer` class which can do whatever is desired. For instance, the  ``WriterAscii::write_vertex`` orders the particles within the vertex using their ids, but one can have some different ordering.

**Comment by pavel-demin** [comment]
I've updated the links to my bug report. They are now readable thanks to the web archive.

It seems we have different views on file formats and the corresponding libraries. So let's agree to disagree.

> I'm quite surprised that is not the case for Delphes. Or is it? If it actually is, then one can try to speedup the reading.

I think it should be clear from my previous comments that this is exactly what I am doing. 

Delphes is a framework for **fast** simulation. I try to optimize all its parts for speed. Depending on the multiplicity of events, the reading of events can represent a very important part of the time spent by Delphes on the event processing.

> But, probably the fastest way to read the events inside Delphes still would be to read HepMC3 ROOT trees directly with ROOT, without HepMC3

Delphes provides readers for the formats requested by the researches using Delphes. If the researches want to read files in the HepMC3 text format, I want to provide the fastest possible way for them to read this format.

Since Pythia has recently switched to HepMC3::WriterAscii, the researches using Delphes requested a possibility to read the format produced by HepMC3::WriterAscii.

I didn't receive any request to support HepMC3 ROOT trees.

**Comment by andriish** [comment]
> I've updated the links to my bug report. They are now readable thanks to the web archive. 

So far I don't see the links. Do you mean the files attached to https://sft.its.cern.ch/jira/projects/HEPMC/issues/HEPMC-90?filter=allissues ?

**Comment by pavel-demin** [comment]
> So far I don't see the links.

Here they are:

https://web.archive.org/web/http://savannah.cern.ch/bugs/?98781
https://web.archive.org/web/http://savannah.cern.ch/task/?40898

They are the same as in one of my previous comment.

I didn't know that my bug report is still available via [sft.its.cern.ch](https://sft.its.cern.ch/jira/projects/HEPMC/issues/HEPMC-90). Thank you for the link.

Unfortunately the attached files are not available but I don't think they are still relevant after nine years. The main idea is explained in the text and is used in [this class](https://github.com/delphes/delphes/blob/master/classes/DelphesStream.cc). Nothing really special. I tested several methods to read and parse files and chose the fastest one I could find. I was surprised that it was much faster than the method provided by the HepMC library. That is why I submitted the bug report.

**Comment by andriish** [comment]
Hi @pavel-demin ,

> Here they are:

Thanks a lot! Very interesting.

However, I don't think that the issue is relevant anymore. The code from the "bugreport" implements *partial* reading of
HepMC2 format, so I've tried to do the same with HepMC3.

The fastest code from your proposal/"bugreport" is `ReadHepMC_fgets_sscan`. I've tested it on my machine (CentOS8 x86_64)
with a typical  HepMC2 file  from here https://rivet.hepforge.org/downloads/?f=LHC-Zee-MEPS1.hepmc.gz and compared the results to HepMC3 using the attached reader in three variations

1) The baseline configuration,  equivalent to the usage of `ReaderAsciiHepMC2`
```
$CXX $CXXFLAGS  -o main.exe    main.cpp ReaderAsciiHepMC2Simple.cc  -lHepMC3 
 ```
2) A simplified configuration,  when the reader reads the same info as  `ReadHepMC_fgets_sscan` and creates `HepMC3::GenEvent`
```
$CXX $CXXFLAGS -DSIMPLE  -o mainsimple.exe main.cpp ReaderAsciiHepMC2Simple.cc  -lHepMC3
```
3) Same as 2), but without the creation of `HepMC3::GenEvent`
```
$CXX $CXXFLAGS -DSIMPLE  -DVERYSIMPLE   -o mainverysimple.exe main.cpp ReaderAsciiHepMC2Simple.cc  -lHepMC3
```



Basically, the results for all the compiler I've tried (gcc,glang,intel,pgi/nvidia) are very similar.
 For instance, the user time for gcc version 8.4.1 20210423 (Red Hat 8.4.1-2) (GCC) 

```
 ReadHepMC_fgets_sscan                   0m5.464s
 main.exe                   0m8.535s
 mainsimple.exe                   0m5.340s 
 mainverysimple.exe                   0m4.642s
```
Means: the fastest of the proposed codes is, indeed, faster than the standard WriterAsciiHepMC2, but only because it reads less information and does not build `GenEvent`. Once the `WriterAsciiHepMC2` starts to read exactly the same information, it shows (slightly) better performance.  Once the building of GenEvent is disabled, WriterAsciiHepMC2 starts to be much faster, up to ~30-35% for pgi/nvidia.




Best regards,

Andrii

P.S. The used flags were the recommended flags fro RedHat 
```
-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
```

[ReaderAsciiHepMC2Simple.zip](https://github.com/delphes/delphes/files/6576438/ReaderAsciiHepMC2Simple.zip)

**Comment by pavel-demin** [comment]
> The fastest code from your proposal/"bugreport" is `ReadHepMC_fgets_sscan`

For me, `ReadHepMC_getline_strtox` is still the fastest one. It's twice faster than `ReadHepMC_fgets_sscan`.

Have you tested `ReadHepMC_strtox.cpp`?

I think with `ReadHepMC_fgets_strtox` from `ReadHepMC_strtox.cpp` your table will look like the following:

```
 ReadHepMC_fgets_strtox     0m2.732s (calculated as 5.464/2)

 ReadHepMC_fgets_sscan      0m5.464s
 main.exe                   0m8.535s
 mainsimple.exe             0m5.340s
 mainverysimple.exe         0m4.642s
```
> because it reads less information and does not build GenEvent

I've also noticed that building GenEvent is slow. I think this is because of the massive usage of `shared_ptr` and the multiple allocations/deallocations for each event. I think using object pools and getting rid of `shared_ptr` would greatly improve performance of the HepMC3 library.

**Comment by andriish** [comment]
> ReadHepMC_fgets_strtox

OK, OK.  I've confused the sources.
Yes, ReadHepMC_fgets_strtox runs in 0m2.630.

Very interesting. The difference is 2 sec, i.e 2*10^-4 per event.
I'm still not convinced it is important, but  pushing the optimization to the limits one could use 
https://github.com/fastfloat/fast_float 

With a simple 
```
#define ATOI(x)  strtol(x,nullptr,10)
#include "fast_float.h"
inline double ATOF(const char* x) { double v; auto r = fast_float::from_chars(x,nullptr,v); return v;} 
```
and replacement atoi -> ATOI, atof -> ATOF I get 
0m1.967s for the `mainverysimple.exe`

Best regards,

Andrii

**Comment by pavel-demin** [comment]
I just realized that your first name is the same as one of the HepMC3 developers. Is it a coincidence or you are the developer of HepMC3?

**Comment by andriish** [comment]
I am.

**Comment by pavel-demin** [comment]
Oops. I hope I didn't upset you with my criticism.

I've finally found how to fix the order of the decay products in my code reading the HepMC3 files.

Here's a comparison of two readers:
```
# with HepMC3::ReaderAscii
# time ./DelphesHepMC3 cards/delphes_card_CMS.tcl test.root test.hepmc3
real    0m4.768s
user    0m4.585s
sys     0m0.160s

# with DelphesHepMC3Reader
# time ./DelphesHepMC3 cards/delphes_card_CMS.tcl test.root test.hepmc3

real    0m3.648s
user    0m3.487s
sys     0m0.133s
```

The slowness of the HepMC3 reader increases the total runtime by 30%.

**Comment by andriish** [comment]
> criticism

That is important to know what people want and what they don't want. I.e. in the case of Delphes the reading speed from ASCII files seems to be important. I'm quite surprised, but well, it is what it is.

> The slowness of the HepMC3 reader increases the total runtime by 30%.

Ok, not sure if the whole difference can be eliminated, but it seems there is a lot of space for improvement of the default readers. On the other hand, I assume  even now DelphesHepMC3Reader and some others can just inherit from HePMC3::Reader and that would eliminate the need of many converters between different formats, as HepMC3::GenEvent can store arbitrary information .

Also

> by 30%.

means that switching to root input could potentially give another 20-30% of speedup.

**Comment by pavel-demin** [comment]
> means that switching to root input could potentially give another 20-30% of speedup

I am not a person who should be convinced to use ROOT. Delphes already uses ROOT.

If the developers of MC generators decide to use HepMC text format as the default output format, the only thing I can do is support this format as the input format for Delphes as well.

However, as I wrote in one of my previous comments, the problem with the ROOT format is that it requires ROOT and ROOT is a huge dependency. I don't think making MC generators depend on ROOT is a good idea.

The two main advantages of the HepMC2 format were:
- the HepMC2 library had no dependencies
- the HepMC2 format was human readable

If HepMC3 now pushes for the ROOT format, then it loses all of its main advantages.

**Comment by pavel-demin** [comment]
> That is important to know what people want and what they don't want.

To give some structure to my feedback, here is a summary of the issues we have identified so far:
- HepMC3::ReaderAscii can be made faster by using strtol/strtod and/or some other optimisations
- building GenEvent can be made faster by using object pools and getting rid of shared_ptr
- HepMC::Asciiv3 format can be made easier to read by grouping decay products (currently products of a single decay are separated by many particles that makes reading difficult). HepMC2 text format was easier to read. So, I consider it a regression. 

If you think HepMC3 developers would be interested in addressing these issues, I can open three separate issues in the HepMC3 GitLab repository.

**Comment by andriish** [comment]
> If HepMC3 now pushes for the ROOT format

It does not. It is what I see from my personal experience.
If there is a need to process a lot of MC events, the way to go (from my experience) is to 1) store events in HepMC3 ROOT files 2) access them as normal TTree 3) process things on PROOF. 
I mean ...  If I use 64 core machine and can process 10^4-10^5 events per second per core... It is fast enough, I even don't disable unused branches...


Concerning the visualization there is a standard viewer in the examples https://gitlab.cern.ch/hepmc/HepMC3/-/tree/master/examples/ViewerExample


The list: it is very useful, thank you.

> HepMC3::ReaderAscii can be made faster by using strtol/strtod and/or some other optimisations

Yes, that should be done. There were suggestions concerning strtol/strtod in the past and that is why now all the char->float,int functions in the readers are standardized, i.e. there were expectations in the past that an optimization will happen.
However, it is not clear if that would be possible to optimize things as well as in the standalone code. 

> building GenEvent can be made faster by using object pools and getting rid of shared_ptr

This is an interesting idea. An approach like that should increase the performance for sure. For sure it is worth it to try.

> by grouping decay products

Yes, the grouping is different.  One can try to improve it, but conceptually it is either all siblings will be written together or mother-daughters.

**Comment by pavel-demin** [comment]
For information.

I've just found one more issue with the HepMC3 format.

On page 13 in [arXiv:1912.08005 [hep-ph]](https://arxiv.org/abs/1912.08005) it's written that HepMC3 format is more compact than the HepMC2 format:

> Asciiv3 is the HepMC3 native plain text format. While being similar to IO_GenEvent, this format is extendable and in comparison to the former requires less storage space, as it does not save meaningless information on particles (e.g. colour flow for hadrons).

However, my observations contradict this statement: 

HepMC2 (2.06.09): 58423705 bytes
HepMC3 (3.02.03): 61033893 bytes

The HepMC2 file was generated by a MC generator and the HepMC3 file is obtained by converting the HepMC2 file to the HepMC3 format.

Here are the links to these files:

http://cp3.irmp.ucl.ac.be/~demin/test.hepmc2.gz
http://cp3.irmp.ucl.ac.be/~demin/test.hepmc3.gz

**Comment by andriish** [comment]
Hi @pavel-demin 


the size, obviously depends on many factors,  but the main one is the content and the precision.
With the same precision the size of HepMC3 is  indeed, smaller than the size of HepMC2 for the typical samples -- see the figures in https://arxiv.org/abs/1912.08005 
The reason is that HepMC2 always stores theta, phi and color flows and HepMC3 do that only if needed. Same true for the vertex weights and vertex position.
To estimate the effect one can assume that for a typical sample for the overwhelming majority the phi, theta and color flows are not set for particles and the vertex weights are empty. Means HepMC3 would save per particle  

- size of color flow,  theta and phi
- size of vertex weights

This gives two floats and one int per particle. The effect for vertices is harder to estimate and some vertices are optimized out in the output. So well, yes, Asciiv3 is more compact. Not for each individual file, but typically that is the case.

The http://cp3.irmp.ucl.ac.be/~demin/test.hepmc3.gz , is, however, affected by a bug in the writer -- the "empty" attributes 
like `A 2 flows ` should not appear in the file. It does not invalidate the event record, just produces extra records in the output.
I've just created a MR that will fix it and with that fix, after the conversion:
```
convert_example.exe -i hepmc2 -o hepmc3 test.hepmc2  1test.hepmc3
convert_example.exe -i hepmc2 -o hepmc2 test.hepmc2  1test.hepmc2
```
I see 

```
test.hepmc2   58423705
1test.hepmc2 63939421
1test.hepmc3 58702725
```
the events in Asciiv3 are ~0.3% larger than the same events in IO_GenEvent as written by HepMC2 library and ~10% smaller than the events in IO_GenEvent as written by HepMC3 library.

That is OK, as the IO_GenEvent in HepMC3 is written in a fixed format explicitly, i.e.  "0" is written as "0.0000000000000000e+00" and not as "0" in the HepMC2.
The same is true for Asciiv3.
From the point of view of disk space, this increases the size of files. It can be checked with 
```
cat  1test.hepmc3 | sed   's/0.0000000000000000e+00/0/g' > 2test.hepmc3
cat  1test.hepmc2 | sed   's/0.0000000000000000e+00/0/g' > 2test.hepmc2
```
that produces 
```
2test.hepmc3  53913213
2test.hepmc2  59168473
```
Practically this could be updated, but there was no request to do that.

Bet regards,

Andrii

**Comment by pavel-demin** [comment]
I am very surprised at your attitude. I have found several problems with the HepMC3 library without even looking too much in depth but from your comments I do not understand if you are interested in fixing them or not.

From what I can read in your comments, I understand that you are confirming all these problems. However, each time you conclude that these problems are not important from your point of view. It is very confusing for me.

Moreover, I think we are abusing the comments to this pull request too much already. I don't think this is the right place to continue discussing the problems of the HepMC3 library.

As I have already mentioned, I can open issues in the HepMC3 GitLab repository but I need a clear confirmation that the HepMC3 developers will be interested in fixing these problems.

**Comment by andriish** [comment]
Hi @pavel-demin ,

> I do not understand if you are interested in fixing them or not.

The bugfix for the empty attribute is already in master.   https://gitlab.cern.ch/hepmc/HepMC3/-/merge_requests/119
For the reader issues I've created https://gitlab.cern.ch/hepmc/HepMC3/-/issues/38  earlier. So for sure these will be fixed.

>  these problems are not important 

All the problems are important, however, so far the optimization has lower priority than bugfixes. Especially if there are no explicit feature/optimization requests.

> Moreover, I think we are abusing the comments to this pull request too much already. 

True.

>  I can open issues in the HepMC3 GitLab repository but I need a clear confirmation that the HepMC3 developers will be interested in fixing these problems.

I see your point, and, assume that,  perhaps, you had a negative experience with the JIRA of HepMC. But, you are very welcome to gitlab of HepMC3 with any requests. And I assure the issues will be fixed. 

Andrii
BEst regards,

Andrii

**Comment by pavel-demin** [comment]
Thank you for the clarification. It's great to see the merge request and the open issue. 

I've just opened a couple of issues:
https://gitlab.cern.ch/hepmc/HepMC3/-/issues/39
https://gitlab.cern.ch/hepmc/HepMC3/-/issues/40

**Pull request closed without merging**
