### PR TITLE
Added vertexing with neutrals

### PR DESCRIPTION
**Pull request by fbedesch**

### CODE REVIEW

**Comment by pavel-demin** [comment]
Thank you for this update.

Could you please create a new directory for the `examples/*.h` and `examples/*.cc` files?

I would also prefer to keep all the `*.C` files in the `examples` directory and not in the top directory.

The `*.C` files that are currently in the top directory contain a path specific to your system.

**Comment by fbedesch** [comment]
I made the changes you requested and made another pull request.
Hope everything is fine now.

              regards,
              Franco

**Comment by pavel-demin** [comment]
Thank you. The directory structure looks OK now.

I see that you removed  `VtxPulls.h` and `VtxPulls.cc` but they are still used by `ExamplePVtxFitEC.C`. Could you please fix this?

**Comment by fbedesch** [comment]
Thanks for noting this. I fixed and pushed.
              Can I do a final pull request now?

              Franco

**Comment by pavel-demin** [comment]
Thank you for fixing `ExamplePVtxFitEC.C`.

I am not sure I understand the reason for a new pull request. Will the new pull request contain additional changes?

This pull request looks fine now. I can merge it now if that is OK with you.

**Comment by fbedesch** [comment]
No other changes. Please go ahead!

              Thanks,
              Franco

**Pull request merged**
