### PR TITLE
Rdev fix relocation

### PR DESCRIPTION
**Pull request by preghenella**
This PR should fix some relocation issues when loading libraries for ROOT analysis

### CODE REVIEW

**Comment by preghenella** [comment]
dear @pavel-demin and @selvaggi 
I noticed that when building the software over our (ALICE) build servers, the package distributed over CVMFS is not usable for ROOT analysis.
The issue seems to be related to the fact that the dictionary is build with absolute paths.

This PR is supposed to fix that, but I still have to test it.
Please, keep it in pause for the time being.
If you have any comments, let me know.

Thanks and best regards,
Roberto

**Comment by preghenella** [comment]
hi @pavel-demin @selvaggi 
FYI, the test within ALICE are successful after this changes and we are able to run Delphes analyses on the GRID.

**Comment by selvaggi** [comment]
dear @preghenella  can you please check why CMAKE compilation fails with ROOTv5:

```
make[2]: *** No rule to make target `../external/ExRootAnalysis/ExRootAnalysis/ExRootClassifier.h', needed by `external/ExRootAnalysis/ExRootAnalysisDict.cxx'.  Stop.
make[2]: *** make[1]: No rule to make target `../classes/classes/DelphesModule.h', needed by `classes/ClassesDict.cxx'.  Stop.
```

**Comment by vvolkl** [comment]
Hi, we had the same issue with delphes installations for key4hep, and are happy to see this fix. May I suggest to simply do an if/else  check for the ROOT version and keep the old invocation of DELPHES_GENERATE_DICTIONARY for ROOTv5? This is of course a sledgehammer and there may be a more elegant solution, but it would be great to merge this in time for the next release.

#93 would include my proposed fix.

**Comment by preghenella** [comment]
ciao @selvaggi sorry I missed your comment...
probably the fix by @vvolkl does all the job. you can close this PR in favour of that one

**Pull request closed without merging**
