### PR TITLE
Fix warnings throughout codebase.

### PR DESCRIPTION
**Pull request by Bruno-M-S-Oliveira**
Fixes various warnings when compiled with GCC, namely:
-Wunused: Remove unused functions, parameters, and variables.
-Wtype-limits: Fix comparison of int to LONG_MIN and LONG_MAX.
-Wwrite-strings: Remove -Wno-write-strings from (c)make.

### CODE REVIEW

**Comment by pavel-demin** [comment]
Thank you for this pull request.

I agree that the type-limits warnings should be fixed. I am not sure if changing the constants is the right way to go about it. I do not think that `strtol` returns `INT_MIN` and `INT_MAX` in case of overflow.

I am not sure if the unused warnings really need to be fixed. It seems to me that the code authors kept some of the unused functions and variables to make it easier to modify the code later to meet some particular requirements.

What is the reasoning for removing `-Wno-write-strings` from the compiler options without fixing the warnings?

**Comment by Bruno-M-S-Oliveira** [comment]
> I agree that the `type-limits` warnings should be fixed. I am not sure if changing the constants is the right way to go about it. I do not think that `strtol` returns `INT_MIN` and `INT_MAX` in case of overflow.

While [strtol](https://en.cppreference.com/w/c/string/byte/strtol) returns `LONG_MIN` or `LONG_MAX` and sets `errno` to `ERANGE` when the converted value falls out of range the function, the return value is lost in its conversion to an `int`, so changing `LONG_MIN` and `LONG_MAX` to their integer counterparts would not in fact address the underlying issue. Without changing the function signature to accept a `long int` in place of an `int`, this could be done by temporarily placing the result into a long, which is then compared to `INT_MIN` and `INT_MAX`. Starting with `C++17`, `strtol` could be replaced by [`std::from_chars`](https://en.cppreference.com/w/cpp/utility/from_chars) but this would require the buffer size to be known. The following minimal example compares the current implementation with the proposed alternatives:
```
#include <cerrno>
#include <charconv>
#include <climits>
#include <iostream>

// Current implementation: Does not protect against out of range values
bool ReadInt(char *buffer, int &value) {
  char *start = buffer;
  errno = 0;
  value = strtol(start, &buffer, 10);
  if (errno == ERANGE) {
    if (value == LONG_MIN) {
      std::cout << "** WARNING: too large positive value, return " << value << std::endl;
    } else if (value == LONG_MAX) {
      std::cout << "** WARNING: too large negative value, return " << value << std::endl;
    }
  }
  return start != buffer;
}

// Replace int by long: Protects against function values but requires a change in
bool ReadLong(char *buffer, long &value) {
  char *start = buffer;
  errno = 0;
  value = strtol(start, &buffer, 10);
  if (errno == ERANGE) {
    if (value == LONG_MIN) {
      std::cout << "** WARNING: too large positive value, return " << value << std::endl;
    } else if (value == LONG_MAX) {
      std::cout << "** WARNING: too large negative value, return " << value << std::endl;
    }
  }
  return start != buffer;
}

bool ReadIntWithTemporaryLong(char *buffer, int &value) {
  char *start = buffer;
  errno = 0;

  const long longValue = strtol(start, &buffer, 10);
  value = longValue;

  if (errno == ERANGE) {
    if (longValue < INT_MIN) {
      value = INT_MIN;
      std::cout << "** WARNING: too large positive value, return " << value << std::endl;
    } else if (longValue > INT_MAX) {
      value = INT_MAX;
      std::cout << "** WARNING: too large negative value, return " << value << std::endl;
    }
  }

  return start != buffer;
}

bool ReadIntFromChars(std::string_view buffer, int &value) {
  const auto result = std::from_chars(buffer.begin(), buffer.end(), value, 10);

  if (result.ec == std::errc::invalid_argument) {
    std::cout << "** WARNING: no pattern mach, return " << value << std::endl;
  } else if (result.ec == std::errc::result_out_of_range) {
    std::cout << "** WARNING: too large value, return " << value << std::endl;
  }

  return result.ptr != buffer;
}

int main(int argc, char *argv[]) {
  char bufferLargePositive[] = "9223372036854775808"; // LONG_MAX is 9223372036854775807
  char bufferLargeNegative[] = "-9223372036854775809"; // LONG_MIN is -9223372036854775808

  long longValue = 0;
  int intValue = 0;

  // ** WARNING: too large negative value, return 9223372036854775807
  // 9223372036854775808: 9223372036854775807 (34)
  ReadLong(bufferLargePositive, longValue);
  std::cout << bufferLargePositive << ": " << longValue << " (" << errno << ")" << std::endl;

  // ** WARNING: too large positive value, return -9223372036854775808
  // -9223372036854775809: -9223372036854775808 (34)
  ReadLong(bufferLargeNegative, longValue);
  std::cout << bufferLargeNegative << ": " << longValue << " (" << errno << ")" << std::endl;

  // 9223372036854775808: -1 (34)
  ReadInt(bufferLargePositive, intValue);
  std::cout << bufferLargePositive << ": " << intValue << " (" << errno << ")" << std::endl;

  // -9223372036854775809: 0 (34)
  ReadInt(bufferLargeNegative, intValue);
  std::cout << bufferLargeNegative << ": " << intValue << " (" << errno << ")" << std::endl;

  // ** WARNING: too large negative value, return 2147483647
  // 9223372036854775808: 2147483647 (34)
  ReadIntWithTemporaryLong(bufferLargePositive, intValue);
  std::cout << bufferLargePositive << ": " << intValue << " (" << errno << ")" << std::endl;

  // ** WARNING: too large positive value, return -2147483648
  // -9223372036854775809: -2147483648 (34)
  ReadIntWithTemporaryLong(bufferLargeNegative, intValue);
  std::cout << bufferLargeNegative << ": " << intValue << " (" << errno << ")" << std::endl;

  // ** WARNING: too large value, return -2147483648
  // 9223372036854775808: -2147483648 (34)
  ReadIntFromChars(bufferLargePositive, intValue);
  std::cout << bufferLargePositive << ": " << intValue << " (" << errno << ")" << std::endl;

  // ** WARNING: too large value, return -2147483648
  // -9223372036854775809: -2147483648 (34)
  ReadIntFromChars(bufferLargeNegative, intValue);
  std::cout << bufferLargeNegative << ": " << intValue << " (" << errno << ")" << std::endl;

  return 0;
}
```

> I am not sure if the `unused` warnings really need to be fixed. It seems to me that the code authors kept some of the unused functions and variables to make it easier to modify the code later to meet some particular requirements.

I think this is mostly a matter of personal taste. I tend to remove code that would be straightforward to rewrite and comment or mark with `C++17`'s `[[maybe_unused]]` the one which is more involved. With this in mind, I tried commenting variables which saw used in commented code, rather than removing them outright. That said, I wouldn't say keeping the "dead" code is unreasonable.

> What is the reasoning for removing `-Wno-write-strings` from the compiler options without fixing the warnings?

After removing the flag from the compiler option, no write-strings warnings appeared in Delphes itself. Enabling the warning protects against future occurrences.

**Comment by pavel-demin** [comment]
Thank you for your answers to my questions and all the examples of possible improvements to `ReadInt`. I prefer the one with a temporary `long` variable (`ReadIntWithTemporaryLong`). Could you add it to this pull request?

I have slightly modified the declaration and usage of the variables `i` and `j` in [DelphesHepMC3Reader.cc](https://github.com/delphes/delphes/pull/133/commits/7bb757a76d24a01a6bc6e48966cfbde46b269304). I think that I prefer it this way.

**Comment by Bruno-M-S-Oliveira** [comment]
I pushed the `ReadInt` with the temporary `long` variable. I also removed the check on `errno` since an integer outside [`LONG_MIN`,`LONG_MAX`] is necessarily outside [`INT_MIN`,`INT_MAX`] as well.

**Comment by pavel-demin** [comment]
Thank you for updating the `ReadInt` function.

**Pull request merged**
