### PR TITLE
PdgCodeFilter update, for ghost-Hadron of jet constituents.

### PR DESCRIPTION
**Pull request by YoungKwonJo**
This update is for adding a option  "RequireKeepGhostBHadron" in modules/PdgCodeFilter.cc .

If we add it, we can take the ghostBhadron particles in the jet constituents.

i have tested it, myself,  
The genjet is not change(affect) by the ghost-bhadron. 
because pt of the bhadron  is very small.

### CODE REVIEW

**Comment by selvaggi** [comment]
Many thanks for this update, and sorry for the late feedback!
Could you please provide some reference and simple explanation on how to make use of this method to define the MC jet flavour? Could this perhaps be made more general by including other jet flavour (e.g charm, strange, gluon , light quark or gluon?)

**Comment by YoungKwonJo** [comment]
for adding ghost bhadron in fastjet clustering.
1. cards/delphes_card_CMS.tcl

add option "RequireKeepGhostBHadron"
change input "InputArray Delphes/allParticles"
change "RequireStatus true"

2. "modules/PdgCodeFilter.cc"
so, keeping the bhadrons and stable particles.
the code is still for only keeping the bhadron.
however, the pt(transverse momentum) is changed for bhadron(if pt is zero, it sets few pt.).

3. And, we can find the bhadrons in the jet constituents.

**Comment by YoungKwonJo** [comment]
i have checked that.
the jet clustering is not affected by bhadrons.  
so the result is same with default configuration.
the difference is only jet constituents (with bhadron) and bhadron pt.

**Comment by YoungKwonJo** [comment]
i updated the code for keeping B/C/S hadron.
This is not for Quark flavor. it is for B/C/S Hadron.

(i guess) light(u/d) hadrons can be stable particles.

**Comment by YoungKwonJo** [comment]
i have updated for keeping all hadron.
and if it is stable particle, the pt is not changed.

**Pull request closed without merging**
